# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94ec4f999e5ff7a0e53cca967072f891642fa06837e6a6f4c7ce9183992c320acfb776b74addd9f14fc12efea9ea2f48164610bf2ad33300a0c6d51a7dd79713

test:
  secret_key_base: ad1b1dec2fc94f21c69de247f2d4de34c96b025459d60577432b467fb7636ad8b29778cd4c324cfa595b29d963c3993cb4caaf0c0d2351684dc60f1b7464b670

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
